export { default as ChakraUiIcon } from './chakra-ui.svg'
export { default as ReactIcon } from './react.svg'
export { default as TypescriptIcon } from './typescript.svg'
export { default as ViteJsIcon } from './vitejs.svg'
export { default as AuthImage } from './authentication.svg'
